package store

import "time"

type Dominion struct {
	Id                                    int
	User                                  *User
	Round                                 *Round
	Realm                                 *Realm
	Race                                  *Race
	Name                                  string
	Prestige                              int
	Peasants                              int
	PeasantsLastHour                      int
	DraftRate                             int
	Morale                                int
	SpyStrength                           float64
	WizardStrength                        float64
	ResourcePlatinum                      int
	ResourceFood                          int
	ResourceLumber                        int
	ResourceMana                          int
	ResourceOre                           int
	ResourceGems                          int
	ResourceTech                          int
	ResourceBoats                         float64
	ImprovementScience                    int
	ImprovementKeep                       int
	ImprovementSpires                     int
	ImprovementForges                     int
	ImprovementWalls                      int
	ImprovementHarbor                     int
	MilitaryDraftees                      int
	MilitaryUnit1                         int
	MilitaryUnit2                         int
	MilitaryUnit3                         int
	MilitaryUnit4                         int
	MilitarySpies                         int
	MilitaryWizards                       int
	MilitaryArchmages                     int
	LandPlain                             int
	LandMountain                          int
	LandSwamp                             int
	LandCavern                            int
	LandForest                            int
	LandHill                              int
	LandWater                             int
	BuildingHome                          int
	BuildingAlchemy                       int
	BuildingFarm                          int
	BuildingSmithy                        int
	BuildingMasonry                       int
	BuildingOreMine                       int
	BuildingGryphonNest                   int
	BuildingTower                         int
	BuildingWizardGuild                   int
	BuildingTemple                        int
	BuildingDiamondMine                   int
	BuildingSchool                        int
	BuildingLumberyard                    int
	BuildingForestHaven                   int
	BuildingFactory                       int
	BuildingGuardTower                    int
	BuildingShrine                        int
	BuildingBarracks                      int
	BuildingDock                          int
	CreatedAt                             time.Time
	UpdatedAt                             time.Time
	DailyPlatinum                         bool
	DailyLand                             bool
	RulerName                             string
	Pack                                  *Pack
	DiscountedLand                        int
	CouncilLastRead                       time.Time
	RoyalGuardActiveAt                    time.Time
	EliteGuardActiveAt                    time.Time
	MonarchyVoteForDominion               *Dominion
	StatAttackingSuccess                  int
	StatDefendingSuccess                  int
	StatEspionageSuccess                  int
	StatSpellSuccess                      int
	StatTotalPlatinumProduction           int
	StatTotalFoodProduction               int
	StatTotalLumberProduction             int
	StatTotalManaProduction               int
	StatTotalOreProduction                int
	StatTotalGemProduction                int
	StatTotalTechProduction               int
	StatTotalBoatsProduction              int
	StatTotalLandExplored                 int
	StatTotalLandConquered                int
	LastTickAt                            time.Time
	StatTotalPlatinumStolen               int
	StatTotalFoodStolen                   int
	StatTotalLumberStolen                 int
	StatTotalManaStolen                   int
	StatTotalOreStolen                    int
	StatTotalGemsStolen                   int
	SpyMastery                            int
	WizardMastery                         int
	StatAssassinateDrafteesDamage         int
	StatAssassinateWizardsDamage          int
	StatMagicSnareDamage                  int
	StatSabotageBoatsDamage               int
	StatDisbandSpiesDamage                int
	StatFireballDamage                    int
	StatLightningBoltDamage               int
	StatEarthquakeHours                   int
	StatGreatFloodHours                   int
	StatInsectSwarmHours                  int
	StatPlagueHours                       int
	HighestLandAchieved                   int
	StatAttackingFailure                  int
	StatDefendingFailure                  int
	StatEspionageFailure                  int
	StatSpellFailure                      int
	StatSpiesExecuted                     int
	StatWizardsExecuted                   int
	StatSpellsReflected                   int
	ForumLastRead                         time.Time
	ProtectionTicksRemaining              int
	LockedAt                              time.Time
	CalculatedNetworth                    int
	Settings                              string
	StatCycloneDamage                     int
	StatWonderDamage                      int
	StatWondersDestroyed                  int
	StatTotalLandLost                     int
	StatSpiesLost                         int
	StatWizardsLost                       int
	TownCrierLastSeen                     time.Time
	WondersLastSeen                       time.Time
	StatTotalPlatinumSpentConstruction    int
	StatTotalLumberSpentConstruction      int
	StatTotalPlatinumSpentExploration     int
	StatTotalPlatinumSpentInvestment      int
	StatTotalLumberSpentInvestment        int
	StatTotalManaSpentInvestment          int
	StatTotalOreSpentInvestment           int
	StatTotalGemsSpentInvestment          int
	StatTotalPlatinumSpentRezoning        int
	StatTotalPlatinumSpentTraining        int
	StatTotalLumberSpentTraining          int
	StatTotalManaSpentTraining            int
	StatTotalOreSpentTraining             int
	StatTotalGemsSpentTraining            int
	StatTotalFoodDecay                    int
	StatTotalLumberDecay                  int
	StatTotalManaDecay                    int
	AIEnabled                             bool
	AIConfig                              string
	AbandonedAt                           time.Time
	BlackGuardActiveAt                    time.Time
	BlackGuardInactiveAt                  time.Time
	StatAssassinateDrafteesDamageReceived int
	StatAssassinateWizardsDamageReceived  int
	StatMagicSnareDamageReceived          int
	StatSabotageBoatsDamageReceived       int
	StatDisbandSpiesDamageReceived        int
	StatFireballDamageReceived            int
	StatLightningBoltDamageReceived       int
	StatEarthquakeHoursReceived           int
	StatGreatFloodHoursReceived           int
	StatInsectSwarmHoursReceived          int
	StatPlagueHoursReceived               int
	StatSpellsDeflected                   int
	MilitaryAssassins                     int
	HourlyActivity                        []byte
	DailyActions                          int
	StatTotalInvestment                   int
	StatBountiesCollected                 int
	Resilience                            int
	FireballMeter                         int
	LightningBoltMeter                    int
	Valor                                 int
	StatMilitaryUnit1Lost                 int
	StatMilitaryUnit2Lost                 int
	StatMilitaryUnit3Lost                 int
	StatMilitaryUnit4Lost                 int
	RacialValue                           float64
	Chaos                                 int
	StatInciteChaosDamage                 int
	StatInciteChaosDamageReceived         int
	StatSpiesCharmed                      int
}

type DominionHistory struct {
	Id        int
	Dominion  *Dominion
	Event     string
	Delta     string
	CreatedAt time.Time
	IP        string
	Device    string
}

type DominionJournal struct {
	Id        int
	Dominion  *Dominion
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DominionQueue struct {
	Dominion  *Dominion
	Source    string
	Resource  string
	Hours     int
	Amount    int
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DominionSpell struct {
	Dominion       *Dominion
	Duration       int
	CastByDominion *Dominion
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Spell          *Spell
}

type DominionTech struct {
	Id        int
	Dominion  *Dominion
	Tech      *Tech
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DominionTick struct {
	Id                       int
	Dominion                 *Dominion
	Prestige                 int
	Peasants                 int
	Morale                   int
	SpyStrength              float64
	WizardStrength           float64
	ResourcePlatinum         int
	ResourceFood             int
	ResourceFoodProduction   int
	ResourceLumber           int
	ResourceLumberProduction int
	ResourceMana             int
	ResourceManaProduction   int
	ResourceOre              int
	ResourceGems             int
	ResourceTech             int
	ResourceBoats            float64
	MilitaryDraftees         int
	MilitaryUnit1            int
	MilitaryUnit2            int
	MilitaryUnit3            int
	MilitaryUnit4            int
	MilitarySpies            int
	MilitaryWizards          int
	MilitaryArchmages        int
	LandPlain                int
	LandMountain             int
	LandSwamp                int
	LandCavern               int
	LandForest               int
	LandHill                 int
	LandWater                int
	DiscountedLand           int
	BuildingHome             int
	BuildingAlchemy          int
	BuildingFarm             int
	BuildingSmithy           int
	BuildingMasonry          int
	BuildingOreMine          int
	BuildingGryphonNest      int
	BuildingTower            int
	BuildingWizardGuild      int
	BuildingTemple           int
	BuildingDiamondMine      int
	BuildingSchool           int
	BuildingLumberyard       int
	BuildingForestHaven      int
	BuildingFactory          int
	BuildingGuardTower       int
	BuildingShrine           int
	BuildingBarracks         int
	BuildingDock             int
	StarvationCasualties     string
	UpdatedAt                time.Time
	HighestLandAchieved      int
	CalculatedNetworth       int
	ResourceFoodDecay        int
	ResourceLumberDecay      int
	ResourceManaDecay        int
	ResourceBoatProduction   float64
	ExpiringSpells           string
	MilitaryAssassins        int
	ImprovementScience       int
	ImprovementKeep          int
	ImprovementForges        int
	ImprovementWalls         int
	Resilience               int
	FireballMeter            int
	LightningBoltMeter       int
}